name: Example
on:
  issues:
    types: [opened]
env:
  PROJECT_OWNER: nn-nissy1010
  PROJECT_NUMBER: 5
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  example:
    name: Example job
    runs-on: ubuntu-latest
    steps:
    - uses: monry/add-issue-to-project@v1
      id: add-issue-to-project
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        project-owner: ${{ env.PROJECT_OWNER }}
        project-number: ${{ env.PROJECT_NUMBER }}
        issue-id: ${{ github.event.issue.node_id }}
    - name: Output result
      run: |
        echo '${{ steps.add-issue-to-project.outputs.added-project-item-id }}'
        
