name: Issue 作成時に Projects (Beta) に登録する ワークフロー
on:
  issues:
    types: [opened]
env:
  PROJECT_OWNER: nn-nissy1010
  PROJECT_NUMBER: 6
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  manage_project:
    name: Projects (Beta) に登録する ジョブ
    runs-on: ubuntu-latest
    steps:
    - name: Add Issue to Project
      id: add-issue-to-project
      uses: monry/actions-add-issue-to-project@v1
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        project-owner: ${{ env.PROJECT_OWNER }}
        project-number: ${{ env.PROJECT_NUMBER }}
        issue-id: ${{ github.event.issue.node_id }}
        
